### ISSUE TITLE
Possibility to custom system disk with Packer

### ISSUE THREAD

**Issue by sylvain987** [outscale/omi-packer#10]
Hi,

We use Red Hat Enterprise BYOL 8 OMI. We want to build Outscale OMI as closed as possible to the VMWare masters that we build on-promise.

On our backoffice, the system disk contains several FS : /usr, /var, /, ... But on Outscale OMI, we see only a /.

Is it possibility to transform a Red Hat Enterprise BYOL 8 OMI with only a / to OMI with several FS on the system disk with Packer ? 

Regards.

**Comment by outscale-mdr** [comment]
Hello @sylvain987,

We use official upstream images which are single partitioned. You could try to migrate from a single partition fs to a multiple partion fs but it can be tricky. Here are some steps:

```
	1.	create a raw disk: dd if=/dev/zero of=./disk.raw bs=4M count=$($size/4)
	2.	create partitions with fdisk ./disk.raw
	3.	create FS
	4.	mount partitions 
	5.	rsync between images
	6.	update/etc/fstab for the boot
	7.	update grub for / partition
```

**Comment by outscale-mdr** [comment]
However, we do not plan to support this.

**Comment by sylvain987** [comment]
Hi,
Thank for your reply. Ok we continue to use these images with the /.
Regards.
