### ISSUE TITLE
Issue in implementing Windows Example

### ISSUE THREAD

**Issue by olibrius** [outscale/omi-packer#3]
Hello Maintainers, 

I have tried to use packer for Windows machine and i did my best but i'm stocked by the an error when running packer with the following file:

source "osc-bsu" "windows" {
    communicator = "winrm"
    disable_stop_vm = true
    source_omi = "ami-3e5dc2a7"
    omi_name = "WINDOWS-SERVER-2019_{{timestamp}}"
    ssh_interface = "public_ip"
    user_data_file = "scripts/windows/userdata"
    vm_type = "tinav4.c4r4p1"
    winrm_insecure = true
    winrm_use_ssl = true
    winrm_username = "Administrator"
}

build {
    sources = [ "source.osc-bsu.windows" ]

    provisioner "windows-restart" {}
    provisioner "powershell" {
        inline = [
            "Remove-Item -Recurse -Force C:\\Windows\\Outscale\\",
            "Remove-Item -Recurse -Force 'C:\\Users\\Administrator\\AppData\\Roaming\\Microsoft\\Windows\\Start Menu\\Programs\\Startup\\SetupComplete.cmd'",
            "Remove-Item -Recurse -Force 'C:\\Users\\Default\\AppData\\Roaming\\Microsoft\\Windows\\Start Menu\\Programs\\Startup\\SetupComplete.cmd'"
        ]
    }
    provisioner "file" {
        destination = "C:\\Windows\\Outscale\\"
        source = "files/windows/"
    }
    provisioner "powershell" {
        scripts = [ "scripts/windows/sysprep.ps1" ]
    }
}

I got the following errors.

otirat@b2-7-gra3:~/packer/windows/omi-packer$ packer build windows.pkr.hcl
osc-bsu.windows: output will be in this color.

==> osc-bsu.windows: Prevalidating OMI Name: WINDOWS-SERVER-2019_1640089608
==> osc-bsu.windows: Error querying OMI: Post "https://api..outscale.com/oapi/latest/ReadImages": dial tcp: lookup api..outscale.com: no such host
Build 'osc-bsu.windows' errored after 2 milliseconds 652 microseconds: Error querying OMI: Post "https://api..outscale.com/oapi/latest/ReadImages": dial tcp: lookup api..outscale.com: no such host

==> Wait completed after 2 milliseconds 682 microseconds

==> Some builds didn't complete successfully and had errors:
--> osc-bsu.windows: Error querying OMI: Post "https://api..outscale.com/oapi/latest/ReadImages": dial tcp: lookup api..outscale.com: no such host

==> Builds finished but no artifacts were created.

I suppose this comes from an URL issues but you are the experts... I hope it will help..

Sincerely Yours

Olivier TIRAT

**Comment by RomLecat** [comment]
Hello,

It looks like you forgot to set your region.
Please set OUTSCALE_REGION environment variable accordingly (eg. eu-west-2).

**Comment by olibrius** [comment]
Thank you very much ... It appears i add the region and it is working ......

***@***.***:~/packer/windows/omi-packer$ export -p 
OUTSCALE_REGION=eu-west-2
***@***.***:~/packer/windows/omi-packer$ packer build windows.pkr.hcl
osc-bsu.windows: output will be in this color.

==> osc-bsu.windows: Prevalidating OMI Name: WINDOWS-SERVER-2019_1640095136
     osc-bsu.windows: Found Image ID: ami-3e5dc2a7
==> osc-bsu.windows: Creating temporary keypair: 
packer_61c1dda0-2b4d-a2bd-a716-f2f08ee89131
==> osc-bsu.windows: Creating temporary security group for this 
instance: packer_osc_61c1dda1-bda8-7c6c-1601-c3b7f6d1ccfc
==> osc-bsu.windows: Authorizing access to port 5986 from 0.0.0.0/0 in 
the temporary security group...
==> osc-bsu.windows: Launching a source OUTSCALE vm...
==> osc-bsu.windows: Adding tags to source vm
     osc-bsu.windows: Vm ID: i-82f8e919
==> osc-bsu.windows: Waiting for vm (i-82f8e919) to become ready...
     osc-bsu.windows: Adding tag: "Name": "Packer Builder"
==> osc-bsu.windows: Waiting for auto-generated password for vm...
     osc-bsu.windows: It is normal for this process to take up to 15 
minutes,
     osc-bsu.windows: but it usually takes around 5. Please wait.
.......

To be continued ... Thanks again ;)


Le 21/12/2021 à 13:30, Romain Lecat a écrit :

**Comment by RomLecat** [comment]
Glad to hear that. I'm closing this issue then, feel free to reopen one if you encounter other issues.

**Comment by olibrius** [comment]
It would be interesting to change the error of outscale packer software when there is some missing input information such as the region. It would probably lower the amount of stupid customer asking for support 
;-) such as myself. 

Olivier TIRAT

**Comment by RomLecat** [comment]
Thanks for the feedback!
I opened an issue about that in Outscale provider: https://github.com/outscale/packer-plugin-outscale/issues/54
